[package]
name = "gordon"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.47.0"
serenity = "0.12"
tokio = { version = "1.27.0",  features = ["macros", "rt-multi-thread"]}
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"