[package]
name = "gordon"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.47.0"
serenity = { version = "0.10", features = ["framework", "client", "gateway"] }
tokio = { version = "1.27.0", features = ["full"] }
anyhow = "1.0"
dotenv = "0.15.0"